### ISSUE TITLE
Explanation for 500MHz system clock

### ISSUE THREAD

**Issue by Kristine1975** [rhythm16/rpi4-bare-metal#1]
https://github.com/rhythm16/rpi4-bare-metal/blob/cbea79d70ea2990e24bc9b3cbe764f6154e226df/README.md?plain=1#L91

> Low level devel said the RPI4's system clock frequency is 500MHz, this is correct in my testing, but I can't find this anywhere, in fact the bcm2711 (the soc on the PI4) peripheral datasheet actually says the system clock frequency is 250MHz on page 10.

The [document on overclocking](https://github.com/raspberrypi/documentation/blob/develop/documentation/asciidoc/computers/config_txt/overclocking.adoc) contains the default frequencies:

> This table gives the default values for the options on various Raspberry Pi Models, all frequencies are stated in MHz
>...
> core_freq... Pi4... 500

(yeah, the documentation is all over the place)

**Comment by rhythm16** [comment]
Thanks again :)
