### ISSUE TITLE
Explanation for calculation of PL011 UART baud rate setting

### ISSUE THREAD

**Issue by Kristine1975** [rhythm16/rpi4-bare-metal#2]
https://github.com/rhythm16/rpi4-bare-metal/blob/cbea79d70ea2990e24bc9b3cbe764f6154e226df/README.md?plain=1#L97

> The baudrate setting of the PL011 UART was copied from the exercise solutions, I don't know how it's calculated and is surprised that the value also works for the RPI4.

The [hint is in this file](https://github.com/s-matyukevich/raspberry-pi-os/blob/31fc1481f529ba1a72a8a6bc62dc488b84fc2cdb/exercises/lesson01/2/H-4ND-H/include/peripherals/uart_pl011.h#L17):

> for calculation hint see PrimeCell ® UART (PL011) Technical Reference Manual

Said reference manual is here: https://developer.arm.com/documentation/ddi0183/g/; section 3.3.6 example 3-1 contains an example for how to calculate the baudrate setting (the formulas in section 3.3.4 and 3.3.6 are pretty obscure):

> If the required baud rate is 230400 and `UARTCLK` = 4MHz then:
> Baud Rate Divisor = (4×10^6)/(16×230400) = 1.085
> This means `BRDI` = 1 and `BRDF` = 0.085.
> Therefore, fractional part, m = integer((0.085×64)+0.5) = 5
> Generated baud rate divider = 1+5/64 = 1.078
> Generated baud rate = (4×10^6)/(16×1.078) = 231911
> Error = (231911-230400)/230400 × 100 = 0.656%
> The maximum error using a 6-bit UARTFBRD Register = 1/64×100 = 1.56%. This occurs when m = 1, and the error is cumulative over 64 clock ticks.

There's also table 3-8 with "typical bit rates and their corresponding divisors when UARTCLK is 7.3728MHz" and table 3-9 with "required bit rates and their corresponding integer and fractional divisor values and generated bit rates when UARTCLK is 4MHz".

As both the RPi3 and the RPi4 have a PL011 UART, these calculations work for both models.

(this is a bit like a detective following clues...)

**Comment by rhythm16** [comment]
wow, thanks for the information!
I'll fix it when I get back to this project :)
btw do you happen to know any good learning material on eMMC/SD card driver programming?
I am new to this and I'd like to support block devices to at least load an executable to run, it's a bit too difficult for me to support SD cards just by reading the open source drivers.
Thanks again!

**Comment by Kristine1975** [comment]
> btw do you happen to know any good learning material on eMMC/SD card driver programming?

Not really, I'm afraid. But there's a few sources of information I know of:

* The BCM2835/2837 spec along with [errata](https://elinux.org/BCM2835_datasheet_errata), [graciously combined by someone on Github](https://github.com/raspberrypi/documentation/issues/325#issuecomment-379651504).  Chapter 5 contains a description of the EMMC's registers. It also mentions a document to refer to, SD3.0_Host_AHB_eMMC4.4_Usersguide_ver5.9_jan11_10.pdf, but [that's only available to Arasan's IP customers such as Broadcom](https://forums.raspberrypi.com/viewtopic.php?t=7638#p542030).
* There's [this tutorial for RPi 3](https://github.com/bztsrc/raspi3-tutorial/tree/master/0B_readsector), although it's not really a tutorial, but pretty terse code for accessing the SD card (a close encounter with [clang-format](https://clang.llvm.org/docs/ClangFormat.html) would probably make the code a lot more readable). The [next tutorial](https://github.com/bztsrc/raspi3-tutorial/tree/master/0C_directory) contains code how to read a FAT directory, and the [tutorial after that one](https://github.com/bztsrc/raspi3-tutorial/tree/master/0D_readfile) how to read a file. Again pretty terse code, but probably understandable with the spec next to it.
* [Less terse, almost too verbose (YMMV) is this code](https://github.com/LdB-ECM/Raspberry-Pi/blob/master/SD_FAT32/SDCard.c) for accessing the SD card. It seems to reference [this RPi forums thread about accessing the SD card](https://forums.raspberrypi.com/viewtopic.php?p=1132354) with hints and gotchas, and which in turn references [this not-too-terse, not-too-verbose code](https://github.com/moizumi99/RPiHaribote/blob/master/haribote/sdcard.c).

I haven't done anything with the SD card reader (yet), in fact I just switch to netboot to get rid of the need for an SD card ;-). But maybe this helps.
